### ISSUE TITLE
Please update to Node v0.12

### ISSUE THREAD

**Issue by JamesMessinger** [jinder/path#2]
The `path` module got some new additions in Node v0.12.  It would be great to add them to this package for consistency and feature-parity.
- [`path.win32`](https://nodejs.org/docs/latest/api/path.html#path_path_win32)
- [`path.posix`](https://nodejs.org/docs/latest/api/path.html#path_path_posix)
- [`path.parse()`](https://nodejs.org/docs/latest/api/path.html#path_path_parse_pathstring)
- [`path.format()`](https://nodejs.org/docs/latest/api/path.html#path_path_format_pathobject)

**Comment by jinder** [comment]
This was originally attempted by @AdamBurgess in #1.  Do you want to provide a PR and I'll push live?

**Comment by jinder** [comment]
This has now been done.   Thanks for the PR.

If you fancy doing a version for Node 4.0 and semvar, I'll push that too.
